### PR TITLE
resource/cloudflare_page_rule: Swap `cache_key_fields` to use TypeSet

### LINKED ISSUE #890: Custom Cache Keys always responding with changes
### Terraform version
Terraform v0.13.5

### Affected resource(s)
+ provider registry.terraform.io/cloudflare/cloudflare v2.13.2

- cloudflare_page_rule

### Terraform configuration files

```hcl
resource "cloudflare_page_rule" "page_rule_test" {
  zone_id = var.cloudflare_zone_id

  target = "*${var.cloudflare_zone}/test*"

  priority = 70
  status = "active"
  actions {
    cache_key_fields {
      header {}
      cookie {
        include = [
          "test.anothertest",
          "test.regiontest",
          "test.devicetest",
          "test.testthis",
          "test.hello",
          "test.segmenttest",
          "test.usertype"]
      }
      query_string {}
      user {}
      host {}
    }
  }
}

```

### Debug output
Can be provided when requested as scrubbing is needed

### Panic output
N/A

### Expected behavior
Terraform apply will initially create the resource
Succeeding Terraform plan should show no change

### Actual behavior

Terraform plan is showing that there are changes to cache key fields.
image

### Steps to reproduce
Execute `terraform plan` - Should show that 1 resource will be added
Execute `terraform apply` - This will create the resource

Re-Execute `terraform plan` - Will now show that 1 resource will be changed
Re-Execute `terraform apply` - Will show that 1 resource was changed

### Important factoids
N/A

### Community note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/)
  to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull
  request, please leave a comment

### PR DESCRIPTION
**Pull request by jacobbednarz**
When this resource was introduced, it was done so using `TypeList` for
the inner structure. In Terraform, `TypeList` is used for ordered lists
whereas `TypeSet` is for unordered.

This was working for the most part however the `cache_key_fields` fields
don't place any importance on the order so they are returned from the
API with inconsistent ordering.

To address this issue, we need to swap the representation to be
`TypeSet` and ignore any changes in the ordering when comparing to the
state. With this internal change comes more test coverage -- please take 
a look at the test cases and ensure they match our expectations of the 
defaults and functionality.

Fixes #890

### CODE REVIEW

File: cloudflare/resource_cloudflare_page_rule.go [hunk 1]
```diff
@@ -745,12 +745,12 @@ func transformFromCloudflarePageRuleAction(pageRuleAction *cloudflare.PageRuleAc
 					fieldOutput[fieldID] = fieldValue
 				}
 
-				if fieldOutput["exclude"] == "*" {
-					fieldOutput["exclude"] = []interface{}{}
+				if itemExistsInSlice(fieldOutput["exclude"], "*") {
+					fieldOutput["exclude"] = []interface{}{"*"}
```
Comment (patryk) [inline cloudflare/resource_cloudflare_page_rule.go:749]: We should not add `*` here. It was left out on purpose, so the `ignore` field has its semantics.

**Review by patryk — CHANGES_REQUESTED** [review]

File: cloudflare/resource_cloudflare_page_rule.go (hunk 1 above)
Comment (jacobbednarz) [reply cloudflare/resource_cloudflare_page_rule.go:749]: This was added as the API throws an error when `query_string {}` is passed without any options (_something_ is required). Should we instead use all query string parameters as the default?

Comment (patryk) [reply cloudflare/resource_cloudflare_page_rule.go:749]: My apologies, I thought this was transforming from API to Terraform, not the other way around.

**Comment by jacobbednarz** [comment]
integration suite is now green

```
$ [...] go test -timeout 120s -v -count=1 -run "^(TestCacheKeyFieldsNilValue|TestAccCloudflarePageRuleCacheKey)" github.com/cloudflare/terraform-provider-cloudflare/cloudflare
=== RUN   TestCacheKeyFieldsNilValue
--- PASS: TestCacheKeyFieldsNilValue (0.00s)
=== RUN   TestAccCloudflarePageRuleCacheKeyFieldsBasic
--- PASS: TestAccCloudflarePageRuleCacheKeyFieldsBasic (3.19s)
=== RUN   TestAccCloudflarePageRuleCacheKeyFieldsIgnoreQueryStringOrdering
--- PASS: TestAccCloudflarePageRuleCacheKeyFieldsIgnoreQueryStringOrdering (2.94s)
=== RUN   TestAccCloudflarePageRuleCacheKeyFieldsExcludeAllQueryString
--- PASS: TestAccCloudflarePageRuleCacheKeyFieldsExcludeAllQueryString (3.00s)
=== RUN   TestAccCloudflarePageRuleCacheKeyFields2
--- PASS: TestAccCloudflarePageRuleCacheKeyFields2 (3.28s)
PASS
ok  	github.com/cloudflare/terraform-provider-cloudflare/cloudflare	12.731s
```

**Comment by jacobbednarz** [comment]
@patryk this is ready for a re-review when you have some time

**Review by patryk — APPROVED** [review]
