### PR TITLE
fix: don't concatenate domain during lookup if it is root domain

### LINKED ISSUE #1128: resource/cloudflare_record: `allow_overwrite` fails to find root domain when `@` supplied as name variable
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the provider and it is still present.

### Terraform and Cloudflare provider version

terraform v1.0.2
+ provider registry.terraform.io/cloudflare/cloudflare v2.23.0 (pulled latest version as of today)

### Affected resource(s)

cloudflare_record

### Terraform configuration files

```hcl
resource "cloudflare_record" "example_com" {
  zone_id         = module.zone.id
  name            = "@"
  value           = "google.com"
  type            = "CNAME"
  allow_overwrite = true
}
```

### Debug output

2021-07-12T17:39:45.308+0100 [DEBUG] provider.terraform-provider-cloudflare_99.0.0: -----------------------------------------------------
2021-07-12T17:39:45.308+0100 [DEBUG] provider.terraform-provider-cloudflare_99.0.0: 2021/07/12 17:39:45 [DEBUG] Cloudflare API Request Details:
2021-07-12T17:39:45.308+0100 [DEBUG] provider.terraform-provider-cloudflare_99.0.0: ---[ REQUEST ]---------------------------------------
2021-07-12T17:39:45.308+0100 [DEBUG] provider.terraform-provider-cloudflare_99.0.0: GET /client/v4/zones/xxxxxxxxxxxx/dns_records?name=%40.example.com&page=1&per_page=100&type=CNAME HTTP/1.1
2021-07-12T17:39:45.308+0100 [DEBUG] provider.terraform-provider-cloudflare_99.0.0: Host: api.cloudflare.com
2021-07-12T17:39:45.308+0100 [DEBUG] provider.terraform-provider-cloudflare_99.0.0: User-Agent: HashiCorp Terraform/1.0.1 (+https://www.terraform.io) Terraform Plugin SDK/1.17.2 terraform-provider-cloudflare/dev
2021-07-12T17:39:45.308+0100 [DEBUG] provider.terraform-provider-cloudflare_99.0.0: Authorization: Bearer xxxxxxxxxxxx
2021-07-12T17:39:45.308+0100 [DEBUG] provider.terraform-provider-cloudflare_99.0.0: Content-Type: application/json
2021-07-12T17:39:45.308+0100 [DEBUG] provider.terraform-provider-cloudflare_99.0.0: Accept-Encoding: gzip
2021-07-12T17:39:45.308+0100 [DEBUG] provider.terraform-provider-cloudflare_99.0.0: 
2021-07-12T17:39:45.308+0100 [DEBUG] provider.terraform-provider-cloudflare_99.0.0: 
2021-07-12T17:39:45.308+0100 [DEBUG] provider.terraform-provider-cloudflare_99.0.0: -----------------------------------------------------
2021-07-12T17:39:46.524+0100 [DEBUG] provider.terraform-provider-cloudflare_99.0.0: 2021/07/12 17:39:46 [DEBUG] Cloudflare API Response Details:
2021-07-12T17:39:46.524+0100 [DEBUG] provider.terraform-provider-cloudflare_99.0.0: ---[ RESPONSE ]--------------------------------------
2021-07-12T17:39:46.524+0100 [DEBUG] provider.terraform-provider-cloudflare_99.0.0: HTTP/2.0 200 OK
2021-07-12T17:39:46.524+0100 [DEBUG] provider.terraform-provider-cloudflare_99.0.0: Cf-Cache-Status: DYNAMIC
2021-07-12T17:39:46.524+0100 [DEBUG] provider.terraform-provider-cloudflare_99.0.0: Cf-Ray: 66dbb59c482960bc-DUB
2021-07-12T17:39:46.524+0100 [DEBUG] provider.terraform-provider-cloudflare_99.0.0: Content-Type: application/json
2021-07-12T17:39:46.524+0100 [DEBUG] provider.terraform-provider-cloudflare_99.0.0: Date: Mon, 12 Jul 2021 16:39:46 GMT
2021-07-12T17:39:46.524+0100 [DEBUG] provider.terraform-provider-cloudflare_99.0.0: Expect-Ct: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
2021-07-12T17:39:46.524+0100 [DEBUG] provider.terraform-provider-cloudflare_99.0.0: Server: cloudflare
2021-07-12T17:39:46.524+0100 [DEBUG] provider.terraform-provider-cloudflare_99.0.0: Set-Cookie: __cflb=xxxxxx; SameSite=Lax; path=/; expires=Mon, 12-Jul-21 19:09:47 GMT; HttpOnly
2021-07-12T17:39:46.524+0100 [DEBUG] provider.terraform-provider-cloudflare_99.0.0: Set-Cookie: __cfruid=xxxxx; path=/; domain=.api.cloudflare.com; HttpOnly; Secure; SameSite=None
2021-07-12T17:39:46.524+0100 [DEBUG] provider.terraform-provider-cloudflare_99.0.0: Vary: Accept-Encoding
2021-07-12T17:39:46.525+0100 [DEBUG] provider.terraform-provider-cloudflare_99.0.0: X-Envoy-Upstream-Service-Time: 6
2021-07-12T17:39:46.525+0100 [DEBUG] provider.terraform-provider-cloudflare_99.0.0: 
2021-07-12T17:39:46.525+0100 [DEBUG] provider.terraform-provider-cloudflare_99.0.0: {
2021-07-12T17:39:46.525+0100 [DEBUG] provider.terraform-provider-cloudflare_99.0.0:  "result": [],
2021-07-12T17:39:46.525+0100 [DEBUG] provider.terraform-provider-cloudflare_99.0.0:  "success": true,
2021-07-12T17:39:46.525+0100 [DEBUG] provider.terraform-provider-cloudflare_99.0.0:  "errors": [],
2021-07-12T17:39:46.525+0100 [DEBUG] provider.terraform-provider-cloudflare_99.0.0:  "messages": [],
2021-07-12T17:39:46.525+0100 [DEBUG] provider.terraform-provider-cloudflare_99.0.0:  "result_info": {
2021-07-12T17:39:46.525+0100 [DEBUG] provider.terraform-provider-cloudflare_99.0.0:   "page": 1,
2021-07-12T17:39:46.525+0100 [DEBUG] provider.terraform-provider-cloudflare_99.0.0:   "per_page": 100,
2021-07-12T17:39:46.525+0100 [DEBUG] provider.terraform-provider-cloudflare_99.0.0:   "count": 0,
2021-07-12T17:39:46.525+0100 [DEBUG] provider.terraform-provider-cloudflare_99.0.0:   "total_count": 0,
2021-07-12T17:39:46.525+0100 [DEBUG] provider.terraform-provider-cloudflare_99.0.0:   "total_pages": 1
2021-07-12T17:39:46.525+0100 [DEBUG] provider.terraform-provider-cloudflare_99.0.0:  }
2021-07-12T17:39:46.525+0100 [DEBUG] provider.terraform-provider-cloudflare_99.0.0: }
2021-07-12T17:39:46.525+0100 [DEBUG] provider.terraform-provider-cloudflare_99.0.0: -----------------------------------------------------
2021-07-12T17:39:46.525+0100 [DEBUG] provider.terraform-provider-cloudflare_99.0.0: 2021/07/12 17:39:46 [TRACE] Waiting 8s before next try
2021-07-12T17:39:51.356+0100 [DEBUG] provider.terraform-provider-cloudflare_99.0.0: 2021/07/12 17:39:51 [WARN] WaitForState timeout after 30s
2021-07-12T17:39:51.356+0100 [DEBUG] provider.terraform-provider-cloudflare_99.0.0: 2021/07/12 17:39:51 [WARN] WaitForState starting 30s refresh grace period

### Panic output

_No response_

### Expected output

The provider to overwrite the root record with supplied values when using "@" as name

### Actual output

│ Error: attempted to override existing record however didn't find an exact match
│ 
│   with module.example_com.cloudflare_record.example_com,
│   on example_com/main.tf line 16, in resource "cloudflare_record" "example_com":
│   16: resource "cloudflare_record" "example_com" {

### Steps to reproduce

1. Create a manual CNAME record for root of a domain using @ as the name
2. Use the above code to overwrite the CNAME to something else
3. It fails

### Additional factoids

This will be because the new `allow_overwrite` variable doesn't check that the name is for the root, so it tries to search for a domain that doesn't exist by just concatenating the name variable as: `name + '.' + zone root`

https://github.com/cloudflare/terraform-provider-cloudflare/blob/4b4712be23f25c5ba30005df0883f7eb98308c02/cloudflare/resource_cloudflare_record.go#L382

### References

https://github.com/cloudflare/terraform-provider-cloudflare/pull/1124

### PR DESCRIPTION
**Pull request by MrLemur**
This adds a check to see if domain being queried is the root domain value.

This is required when using `allow_overwrite` as it wil fail to overwrite when the `name` variable equals `@`, representing the root domain.

Closes #1128

### CODE REVIEW

File: cloudflare/resource_cloudflare_record.go [hunk 1]
```diff
@@ -374,13 +374,20 @@ func resourceCloudflareRecordCreate(d *schema.ResourceData, meta interface{}) er
...
 			if strings.Contains(err.Error(), "already exist") {
-
 				if d.Get("allow_overwrite").(bool) {
+					var r cloudflare.DNSRecord
 					log.Printf("[DEBUG] Cloudflare Record already exists however we are overwriting it")
 					zone, _ := client.ZoneDetails(context.Background(), d.Get("zone_id").(string))
-					r := cloudflare.DNSRecord{
-						Name: d.Get("name").(string) + "." + zone.Name,
-						Type: d.Get("type").(string),
+					if d.Get("name").(string) == "@" {
```
Comment (jacobbednarz) [inline cloudflare/resource_cloudflare_record.go:381]: not everyone uses the alias here; if we're adding this, it needs to account for both formats.

**Review by jacobbednarz — CHANGES_REQUESTED** [review]

File: cloudflare/resource_cloudflare_record.go (hunk 1 above)
Comment (MrLemur) [reply cloudflare/resource_cloudflare_record.go:381]: What will the API accept as a valid input for root domain? `""` or `"."`?

Comment (jacobbednarz) [reply cloudflare/resource_cloudflare_record.go:381]: It will be the entire zone name (such as `example.com`) from the API response.

Comment (MrLemur) [reply cloudflare/resource_cloudflare_record.go]: This should be fixed

**Comment by jacobbednarz** [comment]
lgtm! thank you! 🍰
