### PR TITLE
Add placement to deployment config. Fix secrets drif

### LINKED ISSUE #2450: `cloudflare_pages_project` direct upload has a permadiff
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the provider and it is still present.

### Terraform and Cloudflare provider version

```
Terraform v1.4.6
on darwin_arm64
+ provider registry.terraform.io/cloudflare/cloudflare v4.6.0
```

### Affected resource(s)

* cloudflare_pages_project

### Terraform configuration files

```hcl
resource "cloudflare_pages_project" "main" {↲
  account_id        = local.cloudflare_account_id
  name              = "example"
  production_branch = "master"
}
```

### Link to debug output

N/A

### Panic output

_No response_

### Expected output

Plan without changes

### Actual output

```
Terraform will perform the following actions:

  # cloudflare_pages_project.main will be updated in-place
  ~ resource "cloudflare_pages_project" "main" {
        id                = "example"
        name              = "example"
        # (5 unchanged attributes hidden)

      - deployment_configs {
          - preview {
              - always_use_latest_compatibility_date = false -> null
              - compatibility_date                   = "2023-05-15" -> null
              - compatibility_flags                  = [] -> null
              - d1_databases                         = {} -> null
              - durable_object_namespaces            = {} -> null
              - environment_variables                = {} -> null
              - fail_open                            = false -> null
              - kv_namespaces                        = {} -> null
              - r2_buckets                           = {} -> null
              - secrets                              = (sensitive value) -> null
              - usage_model                          = "bundled" -> null
            }
          - production {
              - always_use_latest_compatibility_date = false -> null
              - compatibility_date                   = "2023-05-15" -> null
              - compatibility_flags                  = [] -> null
              - d1_databases                         = {} -> null
              - durable_object_namespaces            = {} -> null
              - environment_variables                = {} -> null
              - fail_open                            = false -> null
              - kv_namespaces                        = {} -> null
              - r2_buckets                           = {} -> null
              - secrets                              = (sensitive value) -> null
              - usage_model                          = "bundled" -> null
            }
        }
    }
```

### Steps to reproduce

1. Add a `cloudflare_pages_project` using direct upload
2. Run `terraform apply`
3. Make no changes to the resource
4. Run `terraform plan`. Expect no planned changes. See a plan that wants to delete the `deployment_configs`.

### Additional factoids

_No response_

### References

_No response_

### LINKED ISSUE #2479: Pages secrets always has drift
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the provider and it is still present.

### Terraform and Cloudflare provider version

Terraform v1.4.6
on windows_amd64
+ provider registry.terraform.io/cloudflare/cloudflare v4.6.0

### Affected resource(s)

cloudflare_pages_project

### Terraform configuration files

```hcl
terraform {
  required_providers {
    cloudflare = {
      source  = "cloudflare/cloudflare"
      version = "4.6.0"
    }
  }
}

provider "cloudflare" {
  api_token = "<API Token with Account:Cloudflare Pages:Edit>"
}

resource "cloudflare_pages_project" "basic_project" {
  account_id        = "8be772befd147a8df540aae0fa15c047"
  name              = "this-is-my-project-01"
  production_branch = "main"
  deployment_configs {
    preview {}
    production {
      secrets = {
        API_URL = "https://api.example.com"
      }
    }
  }
}
```

### Link to debug output

https://gist.github.com/Cyb3r-Jak3/273c1fd1f97df71fad93f7613885a62b

### Panic output

_No response_

### Expected output

There to be no drift on runs

### Actual output

  # cloudflare_pages_project.basic_project will be updated in-place
  ~ resource "cloudflare_pages_project" "basic_project" {
        id                = "this-is-my-project-01"
        name              = "this-is-my-project-01"
        # (5 unchanged attributes hidden)

      ~ deployment_configs {
          ~ production {
              ~ secrets                              = (sensitive value)
                # (10 unchanged attributes hidden)
            }

            # (1 unchanged block hidden)
        }
    }

Plan: 0 to add, 1 to change, 0 to destroy.

### Steps to reproduce

1. Apply the example terraform
2. Run `terraform plan` and see that changes want to be made

### Additional factoids

This is probably due to pages api not returning the secret value

### References

_No response_

### PR DESCRIPTION
**Pull request by Cyb3r-Jak3**
Adds `placement` to `pages_project`. Also fixes #2479

### CODE REVIEW

**Comment by Cyb3r-Jak3** [comment]
I'm proposing devcontainer changes that supports bash history to be persistent if you need to rebuild the devcontainer

File: internal/sdkv2provider/schema_cloudflare_pages_project.go [hunk 1]
```diff
@@ -130,21 +131,25 @@ func resourceCloudflarePagesProjectSchema() map[string]*schema.Schema {
...
 				Type:        schema.TypeMap,
 				Description: "Durable Object namespaces used for Pages Functions.",
 				Optional:    true,
+				Computed:    true,
 			},
 			"d1_databases": {
 				Type:        schema.TypeMap,
 				Description: "D1 Databases used for Pages Functions.",
 				Optional:    true,
+				Computed:    true,
```
Comment (jacobbednarz) [inline internal/sdkv2provider/schema_cloudflare_pages_project.go:146]: why are these bindings being changed to computed?

Comment (Cyb3r-Jak3) [reply internal/sdkv2provider/schema_cloudflare_pages_project.go:146]: They are being sent from the backend.
From a debug log
```
The following problems may be the cause of any confusing errors from downstream operations:
      - .deployment_configs[0].preview[0].d1_databases: planned value cty.MapValEmpty(cty.String) for a non-computed attribute
      - .deployment_configs[0].preview[0].durable_object_namespaces: planned value cty.MapValEmpty(cty.String) for a non-computed attribute
      - .deployment_configs[0].preview[0].kv_namespaces: planned value cty.MapValEmpty(cty.String) for a non-computed attribute
      - .deployment_configs[0].preview[0].usage_model: planned value cty.StringVal("bundled") for a non-computed attribute
      - .deployment_configs[0].preview[0].always_use_latest_compatibility_date: planned value cty.False for a non-computed attribute
      - .deployment_configs[0].preview[0].environment_variables: planned value cty.MapValEmpty(cty.String) for a non-computed attribute
      - .deployment_configs[0].preview[0].fail_open: planned value cty.False for a non-computed attribute
      - .deployment_configs[0].preview[0].r2_buckets: planned value cty.MapValEmpty(cty.String) for a non-computed attribute
      - .deployment_configs[0].preview[0].secrets: sensitive planned value for a non-computed attribute
      - .deployment_configs[0].production[0].always_use_latest_compatibility_date: planned value cty.False for a non-computed attribute
      - .deployment_configs[0].production[0].d1_databases: planned value cty.MapValEmpty(cty.String) for a non-computed attribute
      - .deployment_configs[0].production[0].usage_model: planned value cty.StringVal("bundled") for a non-computed attribute
      - .deployment_configs[0].production[0].durable_object_namespaces: planned value cty.MapValEmpty(cty.String) for a non-computed attribute
      - .deployment_configs[0].production[0].environment_variables: planned value cty.MapValEmpty(cty.String) for a non-computed attribute
      - .deployment_configs[0].production[0].fail_open: planned value cty.False for a non-computed attribute
      - .deployment_configs[0].production[0].kv_namespaces: planned value cty.MapValEmpty(cty.String) for a non-computed attribute
      - .deployment_configs[0].production[0].r2_buckets: planned value cty.MapValEmpty(cty.String) for a non-computed attribute
      -
```
Previously, I recommended using empty deployment configs, but this improves user experience as they won't need to have them.

**Comment by Cyb3r-Jak3** [comment]
This should now fix #2479. When testing, make sure to uncomment the skips for pages test as I forgot a few times 😅

File: internal/sdkv2provider/schema_cloudflare_pages_project.go (hunk 1 above)
Comment (jacobbednarz) [reply internal/sdkv2provider/schema_cloudflare_pages_project.go:146]: this isn't really what `Computed` on a schema attribute is meant to be used for. `Computed` attributes are ones where we don't know the value at runtime but by the end of the operation we should. examples are if we send a payload to generate a new resource but we don't know what the `id` field is since the remote will be generating it. this looks to be more like that we are setting empty schema attributes or conditionally setting them when we should really always be providing a value (even `null` where it makes sense).

**Comment by Cyb3r-Jak3** [comment]
I've undone the changes that I was using with #2479, so this PR will no longer fix that issue. The actual fix will require more work.

File: internal/sdkv2provider/schema_cloudflare_pages_project.go (hunk 1 above)
Comment (Cyb3r-Jak3) [reply internal/sdkv2provider/schema_cloudflare_pages_project.go]: Removed the attempted fix for this

**Comment by jacobbednarz** [comment]
@WalshyDev this lgtm, do you want to have a play here and make sure we've got all the cases covered?

**Comment by jacobbednarz** [comment]
@WalshyDev this lgtm, do you want to have a play here and make sure we've got all the cases covered?

File: .changelog/2480.txt [hunk 2]
```diff
@@ -0,0 +1,6 @@
+```release-note:enhancement
+cloudflare_pages_project: add `placement` to deployment config
+```
+```release-note:bug
+cloudflare_pages_project: set secrets from local schema
```
Comment (jacobbednarz) [inline .changelog/2480.txt:5]:
```suggestion
cloudflare_pages_project: use user provided configuration for secrets in the state handler since the API does not return them
```

**Comment by WalshyDev** [comment]
Yep, let me test it today.

**Comment by WalshyDev** [comment]
Ok, apologies for the delay, this has now been tested. Secrets drift is gone and placement is working well

One thing which may just be a general TF thing so feel free to ignore it, if you remove the entire `placement` block, it doesn't unset the mode. You need to put an empty block to unset it.

**Comment by jacobbednarz** [comment]
> if you remove the entire `placement` block, it doesn't unset the mode. You need to put an empty block to unset it.

this should be something we address here. lack of it the value existing _should_ be the way to remove it from the payload.

**Comment by Cyb3r-Jak3** [comment]
I've fixed the placement issue by always sending a blank placement mode
