### PR TITLE
set logpush job id to "" when not found

### LINKED ISSUE #797: Logpush Job not removed from state when deleted from UI manually
### Terraform Version
v0.12.29 - however this isn't version specific

### Affected Resource(s)
- logpush_job

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration Files
```hcl
resource "cloudflare_logpush_ownership_challenge" "ownership_challenge" {
  zone_id = "d41d8cd98f00b204e9800998ecf8427e"
  destination_conf = "s3://my-bucket-path?region=us-west-2"
}

data "aws_s3_bucket_object" "challenge_file" {
  bucket = "my-bucket-path"
  key    = cloudflare_logpush_ownership_challenge.ownership_challenge.ownership_challenge_filename
}

resource "cloudflare_logpush_job" "example_job" {
  enabled = true
  zone_id = "d41d8cd98f00b204e9800998ecf8427e"
  name = "My-logpush-job"
  logpull_options = "fields=RayID,ClientIP,EdgeStartTimestamp&timestamps=rfc3339"
  destination_conf = "s3://my-bucket-path?region=us-west-2"
  ownership_challenge = aws_s3_bucket_object.challenge_file.body
  dataset = "http_requests"
}
```

### Expected Behavior
The provider should replace the resource if it has been manually deleted outside of Terraform.

### Actual Behavior
The provider catches the 404 and logs an INFO message, however it does not mark the resource for removal.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`
2. Delete the `example_job` Logpush Job via the Cloudflare Dashboard or UI.
3. `terraform plan`
4. result is no change detected.

### Important Factoids
Are there anything atypical about your accounts that we should know? For example: Running in EC2 Classic? Custom version of OpenStack? Tight ACLs?

### PR DESCRIPTION
**Pull request by trjstewart**
fixes #797 

There are currently no tests for the `logpush_job` resource that I could find so I haven't added or amended any. I assume that is because it requires resources external to Cloudflare?

Either way I have build the provider with this change and tested it ourselves and it's working as intended.

### CODE REVIEW

**Comment by jacobbednarz** [comment]
Thanks for putting in the time to fix this one 🍰 As the scenario we're addressing here is when the logpush job isn't in the remote but still in the state, we should include a fix for #795 where attempting to delete the resource fails due to it not being present in the remote. This should then cover off all the cases where the remote is out of sync with the local state.

**Comment by trjstewart** [comment]
Good catch @jacobbednarz, I must be blind because I completely missed that issue. For now this small patch solved our immediate issue and we're just running a custom build of this branch internally for the time being. I won't likely have the time in the next few days to address anything additional for #795 so anyone else is more than welcome to.

File: cloudflare/resource_cloudflare_logpush_job.go [hunk 1]
```diff
@@ -163,10 +164,17 @@ func resourceCloudflareLogpushJobDelete(d *schema.ResourceData, meta interface{}
...
 	if deleteErr != nil {
+		if strings.Contains(err.Error(), "job not found") {
+			log.Printf("[INFO] Could not find logpush job with id: %q", job.ID)
+			d.SetId("")
+			return nil
+		}
 		return fmt.Errorf("error deleting logpush job: %+v", job.ID)
 	}
 
-	return resourceCloudflareLogpushJobRead(d, meta)
```
Comment (jacobbednarz) [inline cloudflare/resource_cloudflare_logpush_job.go:169]: We don't need to call `Read` as there isn't anything to "sync" after we `d.SetId("")`.
