### PR TITLE
 fix random_steering pool weights sent to the API on update from existing value

### LINKED ISSUE #2099: cloudflare_load_balancer rule override randomSteering showing diff after apply
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the provider and it is still present.

### Terraform and Cloudflare provider version

```
Terraform v1.2.5
on linux_amd64
```

### Affected resource(s)

cloudflare_load_balancer

### Terraform configuration files

```hcl
"cloudflare_load_balancer": {
      "staging-arm64-cf-lb-api": {
        "//": {
          "metadata": {
            "path": "us-east-1-staging/staging-arm64-cf-lb-api",
            "uniqueId": "staging-arm64-cf-lb-api"
          }
        },
        "default_pool_ids": [
          "${cloudflare_load_balancer_pool.staging-arm64-cf-lb-pool-api-legacy.id}"
        ],
        "description": "Load balancer for API endpoints.",
        "fallback_pool_id": "${cloudflare_load_balancer_pool.staging-arm64-cf-lb-pool-api-legacy.id}",
        "name": "REDACTED",
        "proxied": true,
        "rules": [
          {
            "condition": "http.request.uri.path contains \"/track\"",
            "name": "Route /track requests",
            "overrides": [
              {
                "default_pools": [
                  "${cloudflare_load_balancer_pool.staging-arm64-cf-lb-pool-api-legacy.id}",
                  "${cloudflare_load_balancer_pool.staging-arm64-cf-lb-pool-api-track.id}"
                ],
                "fallback_pool": "${cloudflare_load_balancer_pool.staging-arm64-cf-lb-pool-api-legacy.id}",
                "random_steering": [
                  {
                    "default_weight": 1,
                    "pool_weights": {
                      "${cloudflare_load_balancer_pool.staging-arm64-cf-lb-pool-api-legacy.id}": 1,
                      "${cloudflare_load_balancer_pool.staging-arm64-cf-lb-pool-api-track.id}": 0
                    }
                  }
                ],
                "steering_policy": "random"
              }
            ]
          },
          {
            "condition": "not ( http.request.uri.path contains \"/track\" )",
            "name": "Route other requests",
            "overrides": [
              {
                "default_pools": [
                  "${cloudflare_load_balancer_pool.staging-arm64-cf-lb-pool-api-legacy.id}",
                  "${cloudflare_load_balancer_pool.staging-arm64-cf-lb-pool-api-other.id}"
                ],
                "fallback_pool": "${cloudflare_load_balancer_pool.staging-arm64-cf-lb-pool-api-legacy.id}",
                "random_steering": [
                  {
                    "default_weight": 1,
                    "pool_weights": {
                      "${cloudflare_load_balancer_pool.staging-arm64-cf-lb-pool-api-legacy.id}": 0,
                      "${cloudflare_load_balancer_pool.staging-arm64-cf-lb-pool-api-other.id}": 1
                    }
                  }
                ],
                "steering_policy": "random"
              }
            ]
          }
        ],
        "zone_id": "REDACTED"
      }
    },
```

### Link to debug output

> 100 MB

### Panic output

_No response_

### Expected output

`"name": "Route /track requests"` should route requests 100% to `${cloudflare_load_balancer_pool.staging-arm64-cf-lb-pool-api-legacy.id}"` and 0% to `${cloudflare_load_balancer_pool.staging-arm64-cf-lb-pool-api-legacy.id}"`.

`"name": "Route other requests"` should route requests 0% to `${cloudflare_load_balancer_pool.staging-arm64-cf-lb-pool-api-legacy.id}"` and 100% to `"${cloudflare_load_balancer_pool.staging-arm64-cf-lb-pool-api-other.id}"`.

### Actual output

`"name": "Route /track requests"` routes requests 100% to `${cloudflare_load_balancer_pool.staging-arm64-cf-lb-pool-api-legacy.id}"` and 0% to `${cloudflare_load_balancer_pool.staging-arm64-cf-lb-pool-api-legacy.id}"`.

`"name": "Route other requests"` routes requests 0% to `${cloudflare_load_balancer_pool.staging-arm64-cf-lb-pool-api-legacy.id}"` and 100% to `"${cloudflare_load_balancer_pool.staging-arm64-cf-lb-pool-api-other.id}"`.

HOWEVER. Terraform Plan continually generates a diff for the 2nd rule:

Apply:
```
Terraform will perform the following actions:

  # cloudflare_load_balancer.staging-arm64-cf-lb-api will be updated in-place
  ~ resource "cloudflare_load_balancer" "staging-arm64-cf-lb-api" {
        id               = "610610173ac16ea20d8b0f4b2d4356ce"
        name             =  REDACTED
        # (11 unchanged attributes hidden)

      ~ rules {
            name       = "Route other requests"
            # (4 unchanged attributes hidden)

          ~ overrides {
                # (6 unchanged attributes hidden)

              + random_steering {
                  + default_weight = 1
                  + pool_weights   = {
                      + "b24bcec45dd2797736966f364254657c" = 0
                      + "d3127f36c93aacd744c43dc85ef3ead8" = 1
                    }
                }
              - random_steering {
                  - default_weight = 1 -> null
                  - pool_weights   = {
                      - "b24bcec45dd2797736966f364254657c" = 1
                      - "d3127f36c93aacd744c43dc85ef3ead8" = 0
                    } -> null
                }
            }
        }

        # (1 unchanged block hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy.
```

Immediately after apply (no other changes made before Plan):

```
Terraform will perform the following actions:

  # cloudflare_load_balancer.staging-arm64-cf-lb-api will be updated in-place
  ~ resource "cloudflare_load_balancer" "staging-arm64-cf-lb-api" {
        id               = "610610173ac16ea20d8b0f4b2d4356ce"
        name             =  REDACTED
        # (11 unchanged attributes hidden)

      ~ rules {
            name       = "Route other requests"
            # (4 unchanged attributes hidden)

          ~ overrides {
                # (6 unchanged attributes hidden)

              + random_steering {
                  + default_weight = 1
                  + pool_weights   = {
                      + "b24bcec45dd2797736966f364254657c" = 0
                      + "d3127f36c93aacd744c43dc85ef3ead8" = 1
                    }
                }
              - random_steering {
                  - default_weight = 1 -> null
                  - pool_weights   = {} -> null
                }
            }
        }

        # (1 unchanged block hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy.
```

Using the opposite version (100 / 0 rather than 0 / 100) version of the second rule does NOT result in a similar diff after apply. The LB during all of this appears to be working as expected.

### Steps to reproduce

1. Plan the configuration indicated by the above JSON.
2. Apply it
3. Rerun Plan with no other changes
4. TF outputs diff where none should exist.

### Additional factoids

_No response_

### References

_No response_

### PR DESCRIPTION
**Pull request by jracollins**
Hiya :wave: 

This PR looks to fix a rather nasty bug of when using load balancer pool weights. 

On creation of the weights, everything is as expected, however on subsequent updates/applies, even though the `terraform plan` and state looks correct, a default empty `"random_steering": {}` is sent to the API, removing any weights entirely. 

This results in scenarios when changing pool weights for 2 pools from (0.98, 0.02) -> (0.95, 0.05) unexpectedly going to 50/50 on apply. 

The `d.GetOk("random_steering")` that calls `expandRandomSteering` returns 1 entry (the desired values) in the set when no existing steering weights exist, and 2 when it does. The first is a default empty value in this scenario and causes the bug.This means that a second apply after the issue does "resolve" and sync to state until the next change. 

This change to always get the last value in the set fixes the issue. I have added a covering update scenario test case that fails without this change. 

Closes #2099

### CODE REVIEW

File: internal/sdkv2provider/resource_cloudflare_load_balancer_test.go [hunk 1]
```diff
@@ -252,6 +252,23 @@ func TestAccCloudflareLoadBalancer_RandomSteering(t *testing.T) {
...
 			},
+			{
+				Config: testAccCheckCloudflareLoadBalancerConfigRandomSteeringUpdate(zoneID, zone, rnd),
+				Check: resource.ComposeTestCheckFunc(
+					testAccCheckCloudflareLoadBalancerExists(name, &loadBalancer),
+					testAccCheckCloudflareLoadBalancerIDIsValid(name, zoneID),
+					// explicitly verify that random_steering has been set
+					resource.TestCheckResourceAttr(name, "random_steering.#", "1"),                     // random_steering appears once
+					resource.TestCheckResourceAttr(name, "random_steering.0.pool_weights.%", "1"),      // one pool configured
+					resource.TestCheckTypeSetElemAttr(name, "random_steering.0.pool_weights.*", "0.4"), // pool weight of 0.3
```
Comment (tc80) [inline internal/sdkv2provider/resource_cloudflare_load_balancer_test.go:263]: nit
```suggestion
					resource.TestCheckTypeSetElemAttr(name, "random_steering.0.pool_weights.*", "0.4"), // pool weight of 0.4
```

File: internal/sdkv2provider/resource_cloudflare_load_balancer_test.go [hunk 2]
```diff
@@ -252,6 +252,23 @@ func TestAccCloudflareLoadBalancer_RandomSteering(t *testing.T) {
...
+					resource.TestCheckResourceAttr(name, "random_steering.0.default_weight", "0.8"),    // default weight of 0.9
```
Comment (tc80) [inline internal/sdkv2provider/resource_cloudflare_load_balancer_test.go:264]: nit: 
```suggestion
					resource.TestCheckResourceAttr(name, "random_steering.0.default_weight", "0.8"),    // default weight of 0.8
```

**Comment by tc80** [comment]
> The first is a default empty value in this scenario and causes the bug

Yikes! Thank you so much @jracollins for putting up this fix! 😄

**Review by tc80 — APPROVED** [review]

File: internal/sdkv2provider/resource_cloudflare_load_balancer_test.go (hunk 2 above)
Comment (jracollins) [reply internal/sdkv2provider/resource_cloudflare_load_balancer_test.go]: Just pushed fixes for both

**Comment by jacobbednarz** [comment]
thanks for the PR here @jracollins. i took your acceptance test and reverted the fix to ensure we are actually addressing the issue here.

```
TF_ACC=1 go test ./internal/sdkv2provider -v -run "^TestAccCloudflareLoadBalancer_RandomSteering" -count 1 -timeout 120m -parallel 1
=== RUN   TestAccCloudflareLoadBalancer_RandomSteering
=== PAUSE TestAccCloudflareLoadBalancer_RandomSteering
=== CONT  TestAccCloudflareLoadBalancer_RandomSteering
    resource_cloudflare_load_balancer_test.go:233: Step 2/2 error: After applying this test step and performing a `terraform refresh`, the plan was not empty.
        stdout
        
        
        Terraform used the selected providers to generate the following execution
        plan. Resource actions are indicated with the following symbols:
          ~ update in-place
        
        Terraform will perform the following actions:
        
          # cloudflare_load_balancer.imkmnzgyhq will be updated in-place
          ~ resource "cloudflare_load_balancer" "imkmnzgyhq" {
                id               = "5726fd6fbe4baa553425f0d75a86cb35"
                name             = "tf-testacc-lb-random-steering-imkmnzgyhq.terraform.cfapi.net"
                # (10 unchanged attributes hidden)
        
              + random_steering {
                  + default_weight = 0.8
                  + pool_weights   = {
                      + "85ee387e4a17bb17909f3636068f28ad" = 0.4
                    }
                }
              - random_steering {
                  - default_weight = 1 -> null
                  - pool_weights   = {} -> null
                }
            }
        
        Plan: 0 to add, 1 to change, 0 to destroy.
--- FAIL: TestAccCloudflareLoadBalancer_RandomSteering (26.35s)
FAIL
FAIL	github.com/cloudflare/terraform-provider-cloudflare/internal/sdkv2provider	26.783s
FAIL
make: *** [testacc] Error 1
```

with your fix

```
TF_ACC=1 go test ./internal/sdkv2provider -v -run "^TestAccCloudflareLoadBalancer_" -count 1 -timeout 120m -parallel 1
=== RUN   TestAccCloudflareLoadBalancer_Import
=== PAUSE TestAccCloudflareLoadBalancer_Import
=== RUN   TestAccCloudflareLoadBalancer_Basic
=== PAUSE TestAccCloudflareLoadBalancer_Basic
=== RUN   TestAccCloudflareLoadBalancer_SessionAffinity
=== PAUSE TestAccCloudflareLoadBalancer_SessionAffinity
=== RUN   TestAccCloudflareLoadBalancer_AdaptiveRouting
=== PAUSE TestAccCloudflareLoadBalancer_AdaptiveRouting
=== RUN   TestAccCloudflareLoadBalancer_LocationStrategy
=== PAUSE TestAccCloudflareLoadBalancer_LocationStrategy
=== RUN   TestAccCloudflareLoadBalancer_RandomSteering
=== PAUSE TestAccCloudflareLoadBalancer_RandomSteering
=== RUN   TestAccCloudflareLoadBalancer_GeoBalanced
=== PAUSE TestAccCloudflareLoadBalancer_GeoBalanced
=== RUN   TestAccCloudflareLoadBalancer_ProximityBalanced
=== PAUSE TestAccCloudflareLoadBalancer_ProximityBalanced
=== RUN   TestAccCloudflareLoadBalancer_Rules
=== PAUSE TestAccCloudflareLoadBalancer_Rules
=== RUN   TestAccCloudflareLoadBalancer_DuplicatePool
=== PAUSE TestAccCloudflareLoadBalancer_DuplicatePool
=== RUN   TestAccCloudflareLoadBalancer_Update
=== PAUSE TestAccCloudflareLoadBalancer_Update
=== RUN   TestAccCloudflareLoadBalancer_CreateAfterManualDestroy
=== PAUSE TestAccCloudflareLoadBalancer_CreateAfterManualDestroy
=== CONT  TestAccCloudflareLoadBalancer_Import
--- PASS: TestAccCloudflareLoadBalancer_Import (16.82s)
=== CONT  TestAccCloudflareLoadBalancer_GeoBalanced
--- PASS: TestAccCloudflareLoadBalancer_GeoBalanced (13.82s)
=== CONT  TestAccCloudflareLoadBalancer_CreateAfterManualDestroy
--- PASS: TestAccCloudflareLoadBalancer_CreateAfterManualDestroy (26.60s)
=== CONT  TestAccCloudflareLoadBalancer_Update
--- PASS: TestAccCloudflareLoadBalancer_Update (26.89s)
=== CONT  TestAccCloudflareLoadBalancer_DuplicatePool
--- PASS: TestAccCloudflareLoadBalancer_DuplicatePool (8.92s)
=== CONT  TestAccCloudflareLoadBalancer_Rules
--- PASS: TestAccCloudflareLoadBalancer_Rules (15.73s)
=== CONT  TestAccCloudflareLoadBalancer_ProximityBalanced
--- PASS: TestAccCloudflareLoadBalancer_ProximityBalanced (15.35s)
=== CONT  TestAccCloudflareLoadBalancer_AdaptiveRouting
--- PASS: TestAccCloudflareLoadBalancer_AdaptiveRouting (15.56s)
=== CONT  TestAccCloudflareLoadBalancer_RandomSteering
--- PASS: TestAccCloudflareLoadBalancer_RandomSteering (27.45s)
=== CONT  TestAccCloudflareLoadBalancer_LocationStrategy
--- PASS: TestAccCloudflareLoadBalancer_LocationStrategy (14.15s)
=== CONT  TestAccCloudflareLoadBalancer_SessionAffinity
--- PASS: TestAccCloudflareLoadBalancer_SessionAffinity (31.32s)
=== CONT  TestAccCloudflareLoadBalancer_Basic
--- PASS: TestAccCloudflareLoadBalancer_Basic (14.78s)
PASS
ok  	github.com/cloudflare/terraform-provider-cloudflare/internal/sdkv2provider	227.924s
```

🏆
