### PR TITLE
resource/custom_hostname: Ensure `Import` stores hostname

### LINKED ISSUE #783: cloudflare_custom_hostname import does not import anything
### Terraform Version
```
Terraform v0.13.2
+ provider registry.terraform.io/cloudflare/cloudflare v2.10.1
+ provider registry.terraform.io/hashicorp/aws v3.1.0
```

### Affected Resource(s)
- cloudflare_custom_hostname

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration Files
```hcl
resource "cloudflare_custom_hostname" "custom_hostname" {
  zone_id = "<ZONE_ID>"
  hostname = "xxxx.xxxx.com"
  custom_origin_server = "xxx.xxxx.com"
  ssl {
    method = "http"
    type = "dv"
    wildcard = "false"
    settings {
      min_tls_version = "1.0"
    }
  }
}

```

### Debug Output
Skipped this to avoid showing secrets

### Panic Output
No panic output

### Expected Behavior
What should have happened?

`terraform show` should have shown info such as hostname after doing an import like so:
`terraform import cloudflare_custom_hostname.custom_hostname <ZONE_ID>/<CUSTOM_HOSTNAME_ID>`

### Actual Behavior
What actually happened?

`terraform show` doesn't show anything, only the IDs previously inputted:

```
resource "cloudflare_custom_hostname" "custom_hostname" {
    id                          = "<CUSTOM_HOSTNAME_ID>"
    ownership_verification      = {
        "name"  = ""
        "type"  = ""
        "value" = ""
    }
    ownership_verification_http = {
        "http_body" = ""
        "http_url"  = ""
    }
    zone_id                     = "<ZONE_ID>"
}

```

### Steps to Reproduce
1. terraform import cloudflare_custom_hostname.custom_hostname <ZONE_ID>/<CUSTOM_HOSTNAME_ID>
2. terraform show

### Important Factoids
None.

### References
#749 #769
#770 #761 #746

### PR DESCRIPTION
**Pull request by jacobbednarz**
Within the `Read` function, we weren't setting the hostname to the
imported value (assuming it was always provided) which has left it
missing in state and subsequently causing replacements unnecessarily.

Fixes #783

### CODE REVIEW

File: cloudflare/resource_cloudflare_custom_hostname_test.go [hunk 1]
```diff
@@ -285,6 +285,32 @@ func TestAccCloudflareCustomHostname_UpdatingZoneForcesNewResource(t *testing.T)
...
+		Steps: []resource.TestStep{
+			{
+				Config: testAccCheckCloudflareCustomHostnameBasic(zoneID, rnd, domain),
+			},
+			{
+				ResourceName:            resourceName,
+				ImportStateIdPrefix:     fmt.Sprintf("%s/", zoneID),
+				ImportState:             true,
+				ImportStateVerify:       true,
+				ImportStateVerifyIgnore: []string{"ssl.#", "ssl.0.certificate_authority", "ssl.0.cname_name", "ssl.0.cname_target", "ssl.0.custom_certificate", "ssl.0.custom_key", "ssl.0.method", "ssl.0.status", "ssl.0.type", "ssl.0.wildcard"},
```
Comment (jacobbednarz) [inline cloudflare/resource_cloudflare_custom_hostname_test.go:308]: As we're not providing these in the resource, the `ImportStateVerify` will always fail. Remove them from the check and just assert on the values we know we have.

**Review by patryk — APPROVED** [review]

**Comment by patryk** [comment]
Thanks.
