### PR TITLE
cloudflare_fallback_domain support for default entries

### LINKED ISSUE #1385: cloudflare_fallback_domain should support default entries so deleting resource does not remove all entries
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the provider and it is still present.

### Terraform and Cloudflare provider version

Terraform v1.1.3
on linux_amd64
+ provider registry.terraform.io/cloudflare/cloudflare v3.7.0

### Affected resource(s)

cloudflare_fallback_domain

### Terraform configuration files

```hcl
resource "cloudflare_fallback_domain" "this" {
  account_id = local.account_id
  domains {
    suffix = "example.com"
    description = "Example domain"
    dns_server = ["1.1.1.1", "2.2.2.2"]
  }
}
```

### Debug output

n/a

### Panic output

_No response_

### Expected output

Per the documentation, I would expect this `example.com` domain to get added to my default set.  Instead, it replaces all domains including all of the default ones.

### Actual output

A plan shows that all other domains are removed:

```
  # cloudflare_fallback_domain.this will be updated in-place
  ~ resource "cloudflare_fallback_domain" "this" {
        id         = "<redacted>"
        # (1 unchanged attribute hidden)

      ~ domains {
          + description = "Example domain"
          ~ dns_server  = [
              + "1.1.1.1",
              + "2.2.2.2",
            ]
          ~ suffix      = "intranet" -> "example.com"
        }
      - domains {
          - dns_server = [] -> null
          - suffix     = "internal" -> null
        }
      - domains {
          - dns_server = [] -> null
          - suffix     = "private" -> null
        }
<truncated>
```

### Steps to reproduce

1. create resource

Only the domains specified are included.

2. delete resource

The set of fallback domains is empty (with no way to reset to the default set of entries).

### Additional factoids

There are actually two problems here, but they're related.

1. The documentation is misleading (it implies a domain is added to existing settings), but also there's no handling of the "default entries" as they're called in the UI.  There should be an additional parameter `include_default_entries` that defaults to `true` and appends the set of domains in the resource to the default entries so that this resource behaves more how folks would assume it behaves (and how the documention implies).
2. When the resource is deleted, the set of domains is emptied instead of reverting back to the default set.  You should be able to control this behavior by enabling/disabling a setting.

### References

_No response_

### PR DESCRIPTION
**Pull request by tjstansell**
This should close #1385 and adds two new options (enabled by default) to support the default entries provided by teams initially and to support restoring those entries on resource deletion.  This updates the behavior to align with the docs and the intended behavior most folks expect, while providing control to customize the behavior.

### CODE REVIEW

File: cloudflare/resource_cloudflare_fallback_domain.go [hunk 1]
```diff
@@ -3,11 +3,20 @@ package cloudflare
...
 	"fmt"
+	"log"
 
 	cloudflare "github.com/cloudflare/cloudflare-go"
 	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema"
 )
 
+// use this since we cannot use const for lists.
+func default_domains() []string {
+	return []string{
```
Comment (jacobbednarz) [inline cloudflare/resource_cloudflare_fallback_domain.go:14]: @kjhandy i can see internally we have this stored; is it something we plan on exposing via the public API to save storing this in Terraform?

File: cloudflare/resource_cloudflare_fallback_domain.go [hunk 2]
```diff
@@ -3,11 +3,20 @@ package cloudflare
...
 	"context"
 	"fmt"
+	"log"
 
 	cloudflare "github.com/cloudflare/cloudflare-go"
 	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema"
 )
 
+// use this since we cannot use const for lists.
+func default_domains() []string {
```
Comment (jacobbednarz) [inline cloudflare/resource_cloudflare_fallback_domain.go:13]: not sure why the linter didn't pick this up but we should use camel casing in Go where the method isn't exported.

```suggestion
func fallbackDefaultDomains() []string {
```

File: cloudflare/schema_cloudflare_fallback_domain.go [hunk 3]
```diff
@@ -10,14 +10,29 @@ func resourceCloudflareFallbackDomainSchema() map[string]*schema.Schema {
 			Type:     schema.TypeString,
 			Required: true,
 		},
+		"include_default_domains": {
+			Optional: true,
+			Type:     schema.TypeBool,
+			Default:  true,
+		},
+		"restore_default_domains_on_delete": {
```
Comment (jacobbednarz) [inline cloudflare/schema_cloudflare_fallback_domain.go:18]: i'm not sure if this attribute makes sense to exist. from the service perspective, the resource is always present we are just modifying it (even before it is configured by the end user). why would we not just update the `Delete` method to send only the default domains instead?

File: cloudflare/resource_cloudflare_fallback_domain.go (hunk 2 above)
Comment (jacobbednarz) [reply cloudflare/resource_cloudflare_fallback_domain.go:13]: alternatively, a `var` will also work here.

File: cloudflare/resource_cloudflare_fallback_domain.go [hunk 4]
```diff
@@ -18,6 +27,7 @@ func resourceCloudflareFallbackDomain() *schema.Resource {
 		Importer: &schema.ResourceImporter{
 			State: resourceCloudflareFallbackDomainImport,
 		},
+		CustomizeDiff: resourceCloudflareFallbackDomainDiff,
```
Comment (jacobbednarz) [inline cloudflare/resource_cloudflare_fallback_domain.go:30]: we should avoid `CustomizeDiff` where we can as it is pretty riddled with edge cases for certain types like `TypeMap` and behaviours on computed fields. it's not really something we want more of.'

if we're using the `CustomizeDiff` here for including the default fallback domains in addition to custom values and avoid permadiffs, we could instead make end users explicitly provide them which feels like expected behaviour given we are customising the already existing resource with their own domains.

Comment (jacobbednarz) [reply cloudflare/resource_cloudflare_fallback_domain.go:30]: a note in the documentation mentioning this for the end user seems like it would address the surprise without any additional work in the provider itself.

File: cloudflare/resource_cloudflare_fallback_domain.go (hunk 1 above)
Comment (tjstansell) [reply cloudflare/resource_cloudflare_fallback_domain.go:14]: I saw the teams api endpoint (api.teams.cloudflare.com) allowed `&reset_defaults=true` during a `DELETE` call, but the public API doesn't allow this.  So, I opted to just duplicate it here.

**Comment by jacobbednarz** [comment]
thanks for the PR! i've gone through and added comments inline but this PR does raise some provider design questions which i don't think we've quite ironed out in the current state.

the two big things:

- `restore_default_domains_on_delete` as an attribute doesn't really make a whole heap of sense if it is the default state, and we return to that state upon no longer managing the resource. like zone settings, we can just set those values in the `Delete` operation back to the original state and leave it at that.
- the `CustomizeDiff` behaviour seems to be trying to do too much implicitly for the end user at the risk of introducing bugs through the types weirdness and incompatibilities. i would recommend a documentation update over this approach mentioning the values need to be explicitly provided should end users wish to include any of the default domains (favouring explicitness in managing the resource).

File: cloudflare/resource_cloudflare_fallback_domain.go (hunk 1 above)
Comment (jacobbednarz) [reply cloudflare/resource_cloudflare_fallback_domain.go:14]: i'll chat to some folks and see what the intention is there. that would make more sense to get publicly supported so the service is the source of truth for this list instead of Terraform.

File: cloudflare/resource_cloudflare_fallback_domain.go (hunk 4 above)
Comment (tjstansell) [reply cloudflare/resource_cloudflare_fallback_domain.go:30]: Yeah. I started this by just updating Delete to reset the entries back to the default set, and then figured, well, if we already have to store the list internally and the existing docs all imply you're _adding_ domains, might as well support the currently documented behavior.  I also tried to point out this documentation problem in #1381, but you immediately closed that issue.

Comment (tjstansell) [reply cloudflare/resource_cloudflare_fallback_domain.go:30]: And without `CustomizeDiff`, we'd be able to change the type to `TypeSet` instead, which is actually more appropriate, since the order doesn't matter.

File: cloudflare/resource_cloudflare_fallback_domain.go (hunk 1 above)
Comment (jacobbednarz) [reply cloudflare/resource_cloudflare_fallback_domain.go]: cool, confirmed with the team this is 👌 if we add it to cloudflare-go, we can do away with this list entirely.

File: cloudflare/resource_cloudflare_fallback_domain.go [hunk 5]
```diff
@@ -8,6 +8,11 @@ import (
 	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema"
 )
 
+var default_domains = []string{
```
Comment (jacobbednarz) [inline cloudflare/resource_cloudflare_fallback_domain.go:11]: we can do away with this now because i added support for this via cloudflare/cloudflare-go#784

File: cloudflare/resource_cloudflare_fallback_domain.go [hunk 6]
```diff
@@ -61,7 +66,7 @@ func resourceCloudflareFallbackDomainDelete(d *schema.ResourceData, meta interfa
 	client := meta.(*cloudflare.API)
 	accountID := d.Get("account_id").(string)
 
-	_, err := client.UpdateFallbackDomain(context.Background(), accountID, nil)
+	_, err := client.UpdateFallbackDomain(context.Background(), accountID, getDefaultDomains())
```
Comment (jacobbednarz) [inline cloudflare/resource_cloudflare_fallback_domain.go:69]:
```suggestion
	err := client.RestoreFallbackDomainDefaults(context.Background(), accountID)
```

**Comment by jacobbednarz** [comment]
pending cloudflare/cloudflare-go#784

File: cloudflare/resource_cloudflare_fallback_domain.go (hunk 5 above)
Comment (tjstansell) [reply cloudflare/resource_cloudflare_fallback_domain.go:11]: great.  any idea when that will be functional in the public api?  doesn't seem to work in my testing.

Comment (jacobbednarz) [reply cloudflare/resource_cloudflare_fallback_domain.go:11]: public documentation is incoming however it already works. it is a DELETE request with the query parameters, and an empty JSON array just as the browser does.

anything that works via the UI has to work with the API as they are serviced from the same infrastructure.

Comment (tjstansell) [reply cloudflare/resource_cloudflare_fallback_domain.go:11]: well, crap. yeah, i was using `&` instead of `?` to separate my query parameters in the curl test ... and the fact it requires a valid json body seemed odd too... but whatever. it does work.
