### PR TITLE
resource/cloudflare_ruleset: conditionally set action parameter "version"

### LINKED ISSUE #1309: Ruleset - Using skip with rules raise error unknown field "version"
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the provider and it is still present.

### Terraform and Cloudflare provider version

```
➜ terraform -v
Terraform v1.0.11
on darwin_amd64
+ provider registry.terraform.io/cloudflare/cloudflare v3.4.0
+ provider registry.terraform.io/hashicorp/random v2.3.1
```

### Affected resource(s)

- Ruleset

### Terraform configuration files

```hcl
resource "cloudflare_ruleset" "account_managed_waf" {
  account_id  = var.cloudflare_account_id
  name        = "managed WAF"
  description = "managed WAF ruleset description"
  kind        = "root"
  phase       = "http_request_firewall_managed"

  rules {
    action = "skip"
    action_parameters {
      rules = { 
        "4814384a9e5d4991b9815dcfc25d2f1f" = "a6be45d4905042b9964ff81dc12e41d2,fa54f3d75ed446e78c22b4ea57b90acf,ec42fac3279943388b6be5ee9182835e,37da7855d2f94f69865365d894a556a4,f2db062052cf453fbe9e93f058ecf7e7,1129dfb383bb42e48466488cf3b37cb1"
      }
    }
    expression = "(cf.zone.name eq \"vence.fun\" and cf.bot_management.score eq 1)"
    description = "Account skip rules OWASP"
    enabled = true
  }

  rules {
    action = "execute"
    action_parameters {
      id = "4814384a9e5d4991b9815dcfc25d2f1f"
      overrides {
        rules {
          id = "6179ae15870a4bb7b2d480d4843b323c"
          action = "block"
          score_threshold = 25
        }
        enabled = true
      }
      matched_data {
         public_key = "zpUlcpNtaNiSUN6LL6NiNz8XgIJZWWG3iSZDdPbMszM="
      }
    }
    expression  = "(cf.zone.name eq \"vence.fun\")"
    description = "Account OWASP vence.fun"
    enabled     = true
  }
}
```

### Debug output

[terraform.log](https://github.com/cloudflare/terraform-provider-cloudflare/files/7521074/terraform.log)

### Panic output

_No response_

### Expected output

I would expect my terraform configuration would works. 

### Actual output

```
╷
│ Error: error updating ruleset with ID "9ed2f9dd430e4d8186b1fa9ba9fb9e05": HTTP status 400: invalid JSON: unknown field "version"
│ 
│   with cloudflare_ruleset.account_managed_waf,
│   on rulesets.tf line 132, in resource "cloudflare_ruleset" "account_managed_waf":
│  132: resource "cloudflare_ruleset" "account_managed_waf" {
│ 
╵
```

### Steps to reproduce

1. Deploy a http_request_firewall_managed configuration without the skip rules
2. Update your configuration with the skip rules
3. You will get the error because the version latest is not expected on skip rules. 

### Additional factoids

As per the file, it seems that `"version": "latest"` is added automatically (line 346). It happens when I update the `http_request_firewall_managed`. At the creation of the phase I do not have the issue. 
I think the version here should be 1. Or it could be higher if the rules ID is updated (but I think that behaviour is not implemented yet). 

### References

_No response_

### PR DESCRIPTION
**Pull request by jacobbednarz**
Updates the action parameter generation process to only set the
"version" value when it is supplied by the end user. This addresses
issues where it was sent unconditionally and prevented some phases from
applying correctly. If the value is set in the configuration, the value
is still sent however, that will be a user configuration error, not a
provider error.

Closes #1309

### CODE REVIEW

File: cloudflare/resource_cloudflare_ruleset_test.go [hunk 1]
```diff
@@ -1990,3 +2020,82 @@ func testAccCheckCloudflareRulesetExposedCredentialCheck(rnd, name, accountID st
...
+    phase       = "http_request_firewall_managed"
+
+    rules {
+      action = "skip"
+      action_parameters {
+        rules = {
+          "4814384a9e5d4991b9815dcfc25d2f1f" = "a6be45d4905042b9964ff81dc12e41d2,fa54f3d75ed446e78c22b4ea57b90acf,ec42fac3279943388b6be5ee9182835e,37da7855d2f94f69865365d894a556a4,f2db062052cf453fbe9e93f058ecf7e7,1129dfb383bb42e48466488cf3b37cb1"
+        }
+      }
+      expression = "(cf.zone.name eq \"%[3]s\")"
```
Comment (jacobbednarz) [inline cloudflare/resource_cloudflare_ruleset_test.go:2074]: @vences i had to remove `cf.bot.management` from the expression here as it is invalid for the phase and resulted in problems. other than that, this is identical to your repro.

**Comment by jacobbednarz** [comment]
acceptance tests are green

```
TF_ACC=1 go test $(go list ./...) -v -run "^TestAccCloudflareRuleset_ConditionallySetActionParameterVersion" -count 1 -parallel 1 -timeout 120m -parallel 1
?   	github.com/cloudflare/terraform-provider-cloudflare	[no test files]
=== RUN   TestAccCloudflareRuleset_ConditionallySetActionParameterVersion
=== PAUSE TestAccCloudflareRuleset_ConditionallySetActionParameterVersion
=== CONT  TestAccCloudflareRuleset_ConditionallySetActionParameterVersion
--- PASS: TestAccCloudflareRuleset_ConditionallySetActionParameterVersion (20.35s)
PASS
ok  	github.com/cloudflare/terraform-provider-cloudflare/cloudflare	20.666s
?   	github.com/cloudflare/terraform-provider-cloudflare/tools/cmd/changelog-check	[no test files]
?   	github.com/cloudflare/terraform-provider-cloudflare/version	[no test files]
```

**Comment by vences** [comment]
Tested in local and it works fine for me!

```
➜  test terraform apply -target cloudflare_ruleset.zone_level_managed_waf
╷
│ Warning: Provider development overrides are in effect
│ 
│ The following provider development overrides are set in the CLI configuration:
│  - cloudflare/cloudflare in /Users/venceslas/go/src/github.com/cloudflare/terraform-provider-cloudflare
│ 
│ The behavior may therefore not match any released version of the provider and applying changes may cause the state to become incompatible with published
│ releases.
╵
cloudflare_ruleset.zone_level_managed_waf: Refreshing state... [id=606386270fc044ffa8c90da53a81817c]

Note: Objects have changed outside of Terraform

Terraform detected the following changes made outside of Terraform since the last "terraform apply":

  # cloudflare_ruleset.zone_level_managed_waf has changed
  ~ resource "cloudflare_ruleset" "zone_level_managed_waf" {
        id          = "606386270fc044ffa8c90da53a81817c"
        name        = "managed WAF"
        # (4 unchanged attributes hidden)

      ~ rules {
            id          = "bd0d78be10e24e07b60e1d50c8afec77"
            # (4 unchanged attributes hidden)

          ~ action_parameters {
                id        = "efb7b8c949ac4650a09736fc376e9aee"
              + products  = []
              + rules     = {}
              + rulesets  = []
                # (2 unchanged attributes hidden)

                # (1 unchanged block hidden)
            }
        }
      ~ rules {
            id          = "d69ec33dee144b3893889ce840e327b9"
            # (4 unchanged attributes hidden)

          ~ action_parameters {
                id        = "4814384a9e5d4991b9815dcfc25d2f1f"
              + products  = []
              + rules     = {}
              + rulesets  = []
                # (2 unchanged attributes hidden)


                # (2 unchanged blocks hidden)
            }
        }
    }


Unless you have made equivalent changes to your configuration, or ignored the relevant attributes using ignore_changes, the following plan may include actions to
undo or respond to these changes.

─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────

Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  # cloudflare_ruleset.zone_level_managed_waf will be updated in-place
  ~ resource "cloudflare_ruleset" "zone_level_managed_waf" {
        id          = "606386270fc044ffa8c90da53a81817c"
        name        = "managed WAF"
        # (4 unchanged attributes hidden)

      ~ rules {
          ~ action      = "execute" -> "skip"
          ~ description = "Execute Cloudflare Managed Ruleset on my zone-level phase entry point ruleset" -> "skip Cloudflare Manage ruleset"
          ~ expression  = "true" -> "(cf.zone.name eq \"domain.xyz\" and http.request.uri.query contains \"skip=rulesets\")"
            id          = "bd0d78be10e24e07b60e1d50c8afec77"
            # (1 unchanged attribute hidden)

          ~ action_parameters {
              - id        = "efb7b8c949ac4650a09736fc376e9aee" -> null
              ~ rulesets  = [
                  + "efb7b8c949ac4650a09736fc376e9aee",
                ]
                # (4 unchanged attributes hidden)

              - overrides {
                  - action  = "challenge" -> null
                  - enabled = false -> null

                  - categories {
                      - action   = "js_challenge" -> null
                      - category = "wordpress" -> null
                      - enabled  = true -> null
                    }

                  - rules {
                      - action          = "block" -> null
                      - enabled         = true -> null
                      - id              = "5de7edfa648c4d6891dc3e7f84534ffa" -> null
                      - score_threshold = 0 -> null
                    }
                  - rules {
                      - action          = "log" -> null
                      - enabled         = true -> null
                      - id              = "75a0060762034a6cb663fd51a02344cb" -> null
                      - score_threshold = 0 -> null
                    }
                }
            }
        }
      ~ rules {
          ~ description = "zone" -> "Execute Cloudflare Managed Ruleset on my zone-level phase entry point ruleset"
            id          = "d69ec33dee144b3893889ce840e327b9"
            # (3 unchanged attributes hidden)

          ~ action_parameters {
              ~ id        = "4814384a9e5d4991b9815dcfc25d2f1f" -> "efb7b8c949ac4650a09736fc376e9aee"
                # (5 unchanged attributes hidden)

              - matched_data {
                  - public_key = "zpUlcpNtaNiSUN6LL6NiNz8XgIJZWWG3iSZDdPbMszM=" -> null
                }

              ~ overrides {
                  + action  = "challenge"
                    # (1 unchanged attribute hidden)

                  ~ categories {
                      + action   = "js_challenge"
                      ~ category = "paranoia-level-2" -> "wordpress"
                      ~ enabled  = false -> true
                    }
                  - categories {
                      - category = "paranoia-level-3" -> null
                      - enabled  = false -> null
                    }
                  - categories {
                      - category = "paranoia-level-4" -> null
                      - enabled  = false -> null
                    }

                  ~ rules {
                      ~ action          = "log" -> "block"
                      ~ enabled         = false -> true
                      ~ id              = "6179ae15870a4bb7b2d480d4843b323c" -> "5de7edfa648c4d6891dc3e7f84534ffa"
                        # (1 unchanged attribute hidden)
                    }
                  + rules {
                      + action  = "log"
                      + enabled = true
                      + id      = "75a0060762034a6cb663fd51a02344cb"
                    }
                }
            }
        }
      + rules {
          + action      = "execute"
          + description = "zone"
          + enabled     = true
          + expression  = "true"

          + action_parameters {
              + id = "4814384a9e5d4991b9815dcfc25d2f1f"

              + matched_data {
                  + public_key = "zpUlcpNtaNiSUN6LL6NiNz8XgIJZWWG3iSZDdPbMszM="
                }

              + overrides {
                  + categories {
                      + category = "paranoia-level-2"
                      + enabled  = false
                    }
                  + categories {
                      + category = "paranoia-level-3"
                      + enabled  = false
                    }
                  + categories {
                      + category = "paranoia-level-4"
                      + enabled  = false
                    }

                  + rules {
                      + action = "log"
                      + id     = "6179ae15870a4bb7b2d480d4843b323c"
                    }
                }
            }
        }
    }

Plan: 0 to add, 1 to change, 0 to destroy.
╷
│ Warning: Resource targeting is in effect
│ 
│ You are creating a plan with the -target option, which means that the result of this plan may not represent all of the changes requested by the current
│ configuration.
│ 
│ The -target option is not for routine use, and is provided only for exceptional situations such as recovering from errors or mistakes, or when Terraform
│ specifically suggests to use it as part of an error message.
╵

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

cloudflare_ruleset.zone_level_managed_waf: Modifying... [id=606386270fc044ffa8c90da53a81817c]
cloudflare_ruleset.zone_level_managed_waf: Modifications complete after 4s [id=606386270fc044ffa8c90da53a81817c]
╷
│ Warning: Applied changes may be incomplete
│ 
│ The plan was created with the -target option in effect, so some changes requested in the configuration may have been ignored and the output values may not be
│ fully updated. Run the following command to verify that no other changes are pending:
│     terraform plan
│ 	
│ Note that the -target option is not suitable for routine use, and is provided only for exceptional situations such as recovering from errors or mistakes, or
│ when Terraform specifically suggests to use it as part of an error message.
```
