### PR TITLE
fixes #1943 - add data_source_rulesets

### LINKED ISSUE #1943: Missing data sources for managed rulesets and rule ids for the new WAF
### Current Terraform and Cloudflare provider version

Terraform version: 1.3.1
Cloudflare provider: 3.24.0 (~> 3.0)

### Description

Add the moment there are no data sources available for the managed rulesets and rules for the new WAF. 
This makes the code less readable / maintainable. Requested change is to add data sources for this so you can loop over and filter them by name / category. This is available for the legacy waf_groups or waf_rules (https://registry.terraform.io/providers/cloudflare/cloudflare/latest/docs/data-sources/cloudflare_waf_groups) 

### Use cases

Making exceptions for specific rules for a specific url. 
Example:
URL A is getting false positives for some of the OWASP rules. Eg. sqli rules are triggered, but there is no sql database behind the service. So you could make exceptions specificly for the rules that are triggered. 

### Potential Terraform configuration

**Managed ruleset id**
```
data "cloudflare_ruleset" "owasp_ruleset" {
  filter {
    name   = ".*OWASP.*"
  }
}
```

**Managed rule id**
```
data "cloudflare_rule" "invalid_character" {
  filter {
    name = ".*920272.*"
  }
}
```

You can then more readable add exceptions to your managed ruleset. 
```
# Exceptions
  rules {
    action  = "skip"
    enabled = true

    action_parameters {
      rules = {
        "${data.owasp_ruleset.id}" = "${data.invalid_character.id},..."
      }
    }
```

Even better would be, to make the value for the rule id in the exception part of the `cloudflare_ruleset` resource a list instead of a comma separated list. You then get something like this:

```
"${data.owasp_ruleset.id}" = [
    "${data.invalid_character.id},",
    "${data.other_data_source.id}",
]
```

### References

_No response_

### PR DESCRIPTION
**Pull request by helloandre**
adds support for `data "cloudflare_rulesets"`

example:

```
data "cloudflare_rulesets" "cmr" {
  zone_id = var.zone_id

  filter {
    name = "Cloudflare Managed Ruleset"
  }
}
```

### CODE REVIEW

File: internal/sdkv2provider/schema_cloudflare_ruleset.go [hunk 1]
```diff
@@ -93,6 +93,19 @@ func resourceCloudflareRulesetSchema() map[string]*schema.Schema {
 						Optional:    true,
 						Description: "Brief summary of the ruleset rule and its intended use.",
 					},
+					"last_updated": {
+						Type:        schema.TypeString,
+						Optional:    true,
+						Description: "The most recent update to this rule.",
+					},
+					// "categories": {
```
Comment (jacobbednarz) [inline internal/sdkv2provider/schema_cloudflare_ruleset.go:101]: is this intentional? unsure if we wanted to introduce this breaking change here.

File: internal/sdkv2provider/data_source_rulesets.go [hunk 2]
```diff
@@ -0,0 +1,278 @@
...
+				fullRulesetRule := map[string]interface{}{
+					"id":           rule.ID,
+					"version":      rule.Version,
+					"action":       rule.Action,
+					"expression":   rule.Expression,
+					"description":  rule.Description,
+					"last_updated": rule.LastUpdated.String(),
+					"ref":          rule.Ref,
+					"enabled":      rule.Enabled,
+					// "categories":   rule.Categories,
```
Comment (jacobbednarz) [inline internal/sdkv2provider/data_source_rulesets.go:182]: if these aren't required, are we able to remove them?

**Comment by jacobbednarz** [comment]
thanks for this @helloandre 🙇 couple of things we need to do in order to get this one over the line:

- run `make docs` to generate the automatic registry documentation. see the [docs](https://github.com/cloudflare/terraform-provider-cloudflare/blob/master/contributing/registry-documentation.md) for how to add examples of your intended usage.
- add some tests. if you're after prior art, check out https://github.com/cloudflare/terraform-provider-cloudflare/blob/master/internal/sdkv2provider/data_source_access_identity_provider_test.go which covers a few scenarios and will help us ensure we don't regress if we ever need to change the functionality here.

there are a couple of questions inline that hopefully make sense but if they don't, let me know and i'll elaborate on them some more 😄

**Comment by jacobbednarz** [comment]
acceptance tests all looking good!

```
TF_ACC=1 go test ./internal/sdkv2provider -v -run "^TestAccCloudflareRulesetsProviderDataSource_" -count 1 -parallel 1 -timeout 120m -parallel 1
=== RUN   TestAccCloudflareRulesetsProviderDataSource_PreventZoneIdAndAccountIdConflicts
--- PASS: TestAccCloudflareRulesetsProviderDataSource_PreventZoneIdAndAccountIdConflicts (2.29s)
=== RUN   TestAccCloudflareRulesetsProviderDataSource_RequireOneOfZoneAccountID
--- PASS: TestAccCloudflareRulesetsProviderDataSource_RequireOneOfZoneAccountID (1.81s)
=== RUN   TestAccCloudflareRulesetsProviderDataSource_FetchOWASPRulesetByName
--- PASS: TestAccCloudflareRulesetsProviderDataSource_FetchOWASPRulesetByName (8.63s)
=== RUN   TestAccCloudflareRulesetsProviderDataSource_FetchOWASPRulesetByID
--- PASS: TestAccCloudflareRulesetsProviderDataSource_FetchOWASPRulesetByID (8.35s)
PASS
ok  	github.com/cloudflare/terraform-provider-cloudflare/internal/sdkv2provider	21.702s
```
